run:
  timeout: "1m"
  issue-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: true
  go: "1.20"
linters:
  enable-all: true
  disable-all: false
  fast: true
  disable:
    - godox
